version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
  build1:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
  #build2:
    #docker:
      #- image: circleci/ruby:2.4
    #steps:
      #- checkout
      #- run: bundle install

workflows:
  version: 2
  my_workflow:
    jobs:
      - build1:
          requires:
            build
      - hold:
          type: approval
          requires:
            - build1
      #- build2

#workflows:
  #version: 2
  #my_workflow:
    #jobs:
      #- build
      #- build1:
          #requires:
            #- build
      #- build2:
          #requires:
            #- build1
      #- hold:
          #type: approval
          #requires:
           #- build2
      #- deploy:
          #requires:
            #- hold

