version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4
    steps:
    - checkout
    #- run: bundle install
    - run: apt-get install nginx
  build2:
    docker:
    - image: circleci/ruby:2.4
    steps:
    - checkout
    - run: bundle install
workflows:
  version: 2
  my_workflow:
    jobs:
    - build
    - build2
