version: 2
jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:6.10-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install 
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # Test the source code
            - run:
                name: Testing
                command: npm run test
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: |
                    if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                        npm run build-qa
                    elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                        npm run build-prod
                    else
                        npm run build-dev
                    fi
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist


#version: 2
#jobs:
  #build:
    #docker:
      #- image: circleci/ruby:2.4
    #working_directory: /tmp/circleci-10
    #steps:
      #- checkout
      #- run: sudo apt-get install python3 -y
      #- store_artifacts:
          #path: /tmp/circleci-10
          #destination: /tmp/circleci-10

  #deploy:
    #machine:
      #enabled: true
    #steps:
      #- checkout
      #- run: sudo apt-get install apache2 -y
      ##- run:
          ##name: Deploy Over SSH
          ##command: |
            ##echo $CIRCLE_BUILD_NUM
            ##ssh ubuntu@52.91.20.223 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "/home/circleci/project"
      #- run:
          #name: conditionally run a deploy job
          #command: |
            #curl -u ${CIRCLE_API_USER_TOKEN} \
            #-d build_parameters[CIRCLE_JOB]=deploy_docker \
            #https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
#workflows:
  #version: 2
  #workflow-test:
    #jobs:
      #- build
      #- deploy:
          #requires:
            #- build
          #filters:
            #branches:
              #only: staging
