version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/java:8 
    steps:
      - checkout
      - run: docker build -t /circleci-10/images/directory test .
     
     
