version: 2

# List of jobs
jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:6.10-browsers
        steps:
           # Steps to be added

    # The deploy job
    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:6.10-browsers
        steps:
            # Steps to be added
            
workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - build
            - deploy





#version: 2
#jobs:
  #build:
    #docker:
      #- image: circleci/ruby:2.4
    #working_directory: /tmp/circleci-10
    #steps:
      #- checkout
      #- run: sudo apt-get install python3 -y
      #- store_artifacts:
          #path: /tmp/circleci-10
          #destination: /tmp/circleci-10

  #deploy:
    #machine:
      #enabled: true
    #steps:
      #- checkout
      #- run: sudo apt-get install apache2 -y
      ##- run:
          ##name: Deploy Over SSH
          ##command: |
            ##echo $CIRCLE_BUILD_NUM
            ##ssh ubuntu@52.91.20.223 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "/home/circleci/project"
      #- run:
          #name: conditionally run a deploy job
          #command: |
            #curl -u ${CIRCLE_API_USER_TOKEN} \
            #-d build_parameters[CIRCLE_JOB]=deploy_docker \
            #https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
#workflows:
  #version: 2
  #workflow-test:
    #jobs:
      #- build
      #- deploy:
          #requires:
            #- build
          #filters:
            #branches:
              #only: staging
