version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:4.2
    steps:
      - checkout:
      - run:
          name:
          command: sudo apt-get install apache2
      - store_artifacts:
          path: /root/project/artifact/artifact.zip
          destination: /root/project/artifact 
    deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            echo $CIRCLE_BUILD_NUM
            ssh ubuntu@18.207.218.164 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "/home/ubuntu/circleci/project/nginx.sh"
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build

   



#jobs:
  #build:
    #docker:
      #- image: circleci/python:3
    #steps:
      #- checkout
      #- run: bundle install
      #- run: echo "i am inside build one "
  #build2:
    #docker:
      #- image: circleci/ruby:2.4
    #steps:
      #- checkout
      #- run: echo "i am inside build two passed"

#workflows:
  #version: 2
  
  #my_workflows:
    #jobs:
      #- build
      #- build2
      #- hold:
          #type: approval
          #requires:
            #- build
      #- build2:
          #requires:
            #- hold


