version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    working_directory: /tmp
    steps:
      - checkout
      - run: sudo apt-get install apache2 -y
      - run: sudo apt-get install python3 -y
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artifact-1/artifact-1.zip
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
      #- store_artifacts:
          #path: ~/
          #destination:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            echo $CIRCLE_BUILD_NUM
            ssh ubuntu@3.83.218.106 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "/home/ubuntu"
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          #filters:
            #branches:
              #only: staging

   


#jobs:
  #build:
    #docker:
      #- image: circleci/python:3
    #steps:
      #- checkout
      #- run: bundle install
      #- run: echo "i am inside build one "
  #build2:
    #docker:
      #- image: circleci/ruby:2.4
    #steps:
      #- checkout
      #- run: echo "i am inside build two passed"
      #ssh ubuntu@18.207.218.164 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "~/project/nginx.sh"

#workflows:
  #version: 2
  
  #my_workflows:
    #jobs:
      #- build
      #- build2
      #- hold:
          #type: approval
          #requires:
            #- build
      #- build2:
          #requires:
            #- hold


