version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    working_directory: /tmp/circleci-10
    steps:
      - checkout
      - run: sudo apt-get install apache2 -y
      - run: sudo apt-get install python3 -y
      #- run:
          #name: Creating Dummy Artifacts
          #command: |
            #echo "my artifact file" > /tmp/artifact-1;
            #mkdir /tmp/artifacts;
            #echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/circleci-10
          destination: /tmp/circleci-10

      #- store_artifacts:
          #path: ~/
          #destination:
  #deploy:
    #machine:
      #enabled: true
    #steps:
      #- checkout
      #- run: sudo apt-get install apache2 -y
      #- run:
          #name: Deploy Over SSH
          #command: |
            #echo $CIRCLE_BUILD_NUM
            #ssh ubuntu@52.91.20.223 BUILD_NO="$CIRCLE_BUILD_NUM" /bin/bash < "/home/circleci/project"
      - deploy:
          name: conditionally run a deploy job
          command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
            if [[ true ]]; then
              curl --user ${CIRCLE_API_USER_TOKEN} \
              --data build_parameters[CIRCLE_JOB]=deploy_docker \
              --data revision=$CIRCLE_SHA1 \
              https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            fi 
workflows:
  version: 2
  workflow-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: staging

