version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4
    steps:
    - checkout
    - run: bundle install
  test:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
workflows:
  version: 2
  my_workflow:
  #build_and_test:
    jobs:
      - build
      - test
