version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4
    steps:
    - checkout
    - run: bundle install
  #build2:
    #docker:
    #- image: circleci/ruby:2.4
    #steps:
    #- checkout
    #- run: bundle install
#workflows:
  #version: 2
  #my_workflow:
    #jobs:
    #- build
    #- build2

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
        filters:
          branches:
            only: staging
        context: staging
      - deploy:
          requires:
            - build
        filters:
          branches:
            only: master
        #context: staging
