version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      #- run: bundle install
      - run: echo "i am inside build one is runging"
  build2:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: echo "i am inside build two passed"

workflows:
  version: 2
  
  my_workflows:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - build2:
          requires:
            - hold


