version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: ubuntu:16.04 
    steps:
      - checkout
      - run: git install
      - run: vim install 
      - run:
          name: Print the Current Time
          command: date
