version: 2
jobs:
  build:
    docker:
      - image: circleci:node:1 
    steps:
      - checkout
      - run: git install
      - run: vim install 
      - run:
          name: Print the Current Time
          command: date
