version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
  build2:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install

workflows:
  version: 2
  
  my-workflow:
    jobs:
      - build
      - build2:
          requires:
            - build
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filter:
            branches:
              only:
                - master
    jobs:
      - build
